Repository DimensionDev/Maskbook, pull requests merged in 2022-05, with the labels that each got.

#6182 fix: bugfix for theme
  packages/mask/src/social-network-adaptor/twitter.com/customization/custom.ts
  packages/mask/src/social-network-adaptor/twitter.com/customization/twitter-color-schema.json
  packages/mask/src/social-network-adaptor/twitter.com/ui-provider.ts
  packages/mask/src/utils/theme/theme-global.d.ts
  packages/mask/src/web3/UI/EthereumChainBoundary.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/SearchBox.tsx
  packages/shared/src/contexts/components/InjectedDialog.tsx
Labels: Test: Tested

#6183 fix: claim all card display
  packages/mask/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/WalletStatusDialog/index.tsx
Labels: Test: Tested

#6204 fix: add scroll when wallet list too long
  packages/icons/general/Gear.tsx
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/extension/popups/pages/Personas/AccountDetail/UI.tsx
  packages/mask/src/extension/popups/pages/Personas/Accounts/UI.tsx
  packages/mask/src/extension/popups/pages/Personas/ConnectedWallets/UI.tsx
  packages/mask/src/extension/popups/pages/Wallet/SelectWallet/index.tsx
  packages/mask/src/extension/popups/pages/Wallet/SwitchWallet/index.tsx
Labels: Test: Tested

#6193 fix: tips entrance ui / ux issues
  packages/icons/brands/EVMChains.tsx
  packages/icons/brands/FLow.tsx
  packages/icons/brands/Solana.tsx
  packages/icons/brands/index.ts
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/components/shared/VerifyWallet/Steps.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/TipsEntranceDialog.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/AddWallet.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/Wallets.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/DisconnectDialog.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/EmptyStatus.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/VerifyAlertLine.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/WalletItem.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/WalletsByNetwork.tsx
  packages/mask/src/plugins/Tips/assets/evmChains.png
  packages/mask/src/plugins/Tips/assets/flow.png
  packages/mask/src/plugins/Tips/assets/solana.png
  packages/mask/src/plugins/Tips/hooks/useSupportedNetworks.ts
  packages/mask/src/plugins/Tips/locales/en-US.json
Labels: Test: Tested

#6214 chore: add post content match
  packages/icons/general/CryptoArt.tsx
  packages/icons/general/Furucombo.tsx
  packages/icons/general/index.ts
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/plugins/CryptoartAI/SNSAdaptor/index.tsx
  packages/mask/src/plugins/CryptoartAI/base.ts
  packages/mask/src/plugins/Furucombo/SNSAdaptor/index.tsx
Labels: Test: Tested

#6114 refactor: application board entries
  cspell.json
  packages/icons/general/AccountBalanceWallet.tsx
  packages/icons/general/LinkOut.tsx
  packages/icons/general/WarningTriangle.tsx
  packages/icons/general/index.ts
  packages/mask/package.json
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/shared-ui/locales/ja-JP.json
  packages/mask/shared-ui/locales/ko-KR.json
  packages/mask/shared-ui/locales/qya-AA.json
  packages/mask/shared-ui/locales/zh-CN.json
  packages/mask/shared-ui/locales/zh-TW.json
  packages/mask/src/components/CompositionDialog/Composition.tsx
  packages/mask/src/components/CompositionDialog/useSubmit.ts
  packages/mask/src/components/DataSource/usePersonaAgainstSNSConnectStatus.ts
  packages/mask/src/components/InjectedComponents/ToolboxUnstyled.tsx
  packages/mask/src/components/shared/ApplicationBoard.tsx
  packages/mask/src/components/shared/ApplicationBoardDialog.tsx
  packages/mask/src/components/shared/ApplicationRecommendArea.tsx
  packages/mask/src/components/shared/ApplicationSettingPluginList.tsx
  packages/mask/src/components/shared/WalletStatusBox/TransactionList.tsx
  packages/mask/src/components/shared/WalletStatusBox/index.tsx
  packages/mask/src/components/shared/WalletStatusBox/usePendingTransactions.tsx
  packages/mask/src/components/shared/assets/react-carousel.es.css
  packages/mask/src/plugins/FindTruman/SNSAdaptor/index.tsx
  packages/mask/src/plugins/ITO/SNSAdaptor/CompositionDialog.tsx
  packages/mask/src/plugins/ITO/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Pets/SNSAdaptor/PetSetDialog.tsx
  packages/mask/src/plugins/Pets/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Pets/base.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/NftRedPacketHistoryItem.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketDialog.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedpacketNftConfirmDialog.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Trader/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Transak/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/ConnectionProgress.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/WalletStatusDialog/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/index.tsx
  packages/mask/src/social-network-adaptor/facebook.com/injection/Toolbar.tsx
  packages/mask/src/social-network-adaptor/facebook.com/injection/ToolbarUI.tsx
  packages/mask/src/social-network-adaptor/minds.com/injection/ToolboxHint.tsx
  packages/mask/src/social-network-adaptor/minds.com/injection/ToolboxHint_UI.tsx
  packages/mask/src/social-network-adaptor/twitter.com/injection/ToolboxHint.tsx
  packages/mask/src/social-network-adaptor/twitter.com/injection/ToolboxHint_UI.tsx
  packages/mask/src/social-network/types.ts
  packages/mask/src/social-network/ui.ts
  packages/plugin-infra/src/types.ts
  packages/plugins/CrossChainBridge/src/SNSAdaptor/index.tsx
  packages/plugins/FileService/src/SNSAdaptor/MainDialog.tsx
  packages/plugins/Wallet/src/messages.ts
  packages/shared/src/UI/components/ApplicationEntry/index.tsx
  pnpm-lock.yaml
Labels: Test: Tested

#6225 fix: adjust layout of dialog title
  packages/mask/src/plugins/Tips/components/TipDialog.tsx
  packages/mask/src/social-network-adaptor/twitter.com/ui-provider.ts
  packages/shared/src/contexts/components/InjectedDialog.tsx
Labels: Test: Pending

#6243 fix: popup steps show snackbar issues
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/components/shared/VerifyWallet/Steps.tsx
  packages/mask/src/extension/popups/pages/Personas/VerifyWallet/index.tsx
Labels: Test: Tested

#6242 fix: check next id verified
  packages/mask/src/components/DataSource/useNextID.ts
  packages/mask/src/components/shared/ApplicationBoard.tsx
Labels: Test: Tested

#6229 fix: backup not restore correctly
  packages/mask/background/services/__utils__/convert.ts
  packages/mask/background/services/backup/internal_restore.ts
  packages/shared-base/src/Identifier/ec-key.ts
Labels: Test: Tested

#6234 fix: add linked persona identifier to profile information
  packages/dashboard/src/pages/Personas/components/ContactsTable/index.tsx
  packages/mask/background/services/__utils__/convert.ts
  packages/mask/src/components/DataSource/useActivatedUI.ts
  packages/mask/src/components/shared/SelectProfileUI/ProfileInList.tsx
  packages/mask/src/components/shared/SelectProfileUI/SelectProfileUI.tsx
  packages/mask/src/components/shared/SelectRecipients/ProfileInList.tsx
  packages/mask/src/plugins/ITO/SNSAdaptor/CompositionDialog.tsx
  packages/mask/src/plugins/ITO/SNSAdaptor/CreateForm.tsx
  packages/mask/src/plugins/Polls/SNSAdaptor/PollsDialog.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketDialog.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketERC20Form.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketPast.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedpacketNftConfirmDialog.tsx
  packages/mask/src/social-network-adaptor/facebook.com/utils/getProfileIdentifier.ts
  packages/mask/src/social-network-adaptor/minds.com/collecting/post.ts
  packages/mask/src/social-network-adaptor/twitter.com/collecting/post.ts
  packages/mask/src/social-network-adaptor/twitter.com/injection/MaskIcon.tsx
  packages/mask/src/social-network-adaptor/twitter.com/ui-provider.ts
  packages/mask/src/social-network-adaptor/utils.ts
  packages/mask/src/social-network/ui.ts
  packages/shared-base/src/Persona/type.ts
Labels: Test: Tested

#6245 fix(xdai): temporally disable 1559 feature, since failing of gas estimation
  packages/web3-shared/evm/assets/chains.json
Labels: Test: Tested

#6218 refactor: the connect wallet dialog
  packages/mask/src/components/shared/WalletStatusBox/index.tsx
  packages/mask/src/extension/background-script/EthereumServices/provider.ts
  packages/mask/src/extension/popups/components/LoadingPlaceholder/index.tsx
  packages/mask/src/plugins/Wallet/Dashboard/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/WalletConnectQRCodeDialog/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/WalletStatusDialog/index.tsx
  packages/shared/src/contexts/components/InjectedDialog.tsx
Labels: Test: Failed

#6252 fix: remove useless style
  packages/icons/general/Gear.tsx
  packages/icons/general/index.ts
  packages/mask/src/components/shared/ApplicationBoardDialog.tsx
  packages/mask/src/social-network-adaptor/twitter.com/ui-provider.ts
  packages/shared/src/contexts/components/InjectedDialog.tsx
Labels: Test: Tested

#6201 feat: improve mask compose
  packages/dashboard/src/locales/en-US.json
  packages/icons/general/Copy.tsx
  packages/icons/general/SearchEmpty.tsx
  packages/icons/general/Send.tsx
  packages/icons/general/index.ts
  packages/mask/background/services/crypto/encryption.ts
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/shared-ui/locales/ja-JP.json
  packages/mask/shared-ui/locales/ko-KR.json
  packages/mask/shared-ui/locales/qya-AA.json
  packages/mask/shared-ui/locales/zh-CN.json
  packages/mask/shared-ui/locales/zh-TW.json
  packages/mask/src/components/CompositionDialog/BadgeRenderer.tsx
  packages/mask/src/components/CompositionDialog/Composition.tsx
  packages/mask/src/components/CompositionDialog/CompositionUI.tsx
  packages/mask/src/components/CompositionDialog/EncryptionMethodSelector.tsx
  packages/mask/src/components/CompositionDialog/EncryptionTargetSelector.tsx
  packages/mask/src/components/CompositionDialog/PluginEntryRender.tsx
  packages/mask/src/components/CompositionDialog/PopoverListItem.tsx
  packages/mask/src/components/CompositionDialog/PopoverListTrigger.tsx
  packages/mask/src/components/CompositionDialog/TypedMessageEditor.tsx
  packages/mask/src/components/CompositionDialog/useSubmit.ts
  packages/mask/src/components/InjectedComponents/DecryptedPost/DecryptedPostSuccess.tsx
  packages/mask/src/components/InjectedComponents/SetupGuide.tsx
  packages/mask/src/components/shared/SelectRecipients/ProfileInList.tsx
  packages/mask/src/components/shared/SelectRecipients/SelectRecipients.tsx
  packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
  packages/mask/src/components/shared/SelectRecipients/useTwitterIdByWalletSearch.tsx
  packages/mask/src/social-network/types.ts
  packages/mask/src/social-network/utils/create-post-context.ts
  packages/mask/src/utils/components/Avatar.tsx
  packages/plugins/FileService/src/SNSAdaptor/index.tsx
  packages/shared-base/src/Identifier/ec-key.ts
  packages/shared-base/src/Messages/Mask.ts
  packages/shared-base/src/Persona/type.ts
  packages/shared/src/contexts/components/InjectedDialog.tsx
Labels: Test: Tested

#6277 fix: persona sign length
  packages/mask/background/services/identity/persona/sign.ts
Labels: Test: Tested

#6278 fix: serializer bug
  packages/shared-base/src/serializer/index.ts
Labels: Test: Tested

#6279 fix: twitter id selector
  packages/mask/src/components/DataSource/useNextID.ts
  packages/mask/src/social-network-adaptor/twitter.com/collecting/identity.ts
  packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts
  packages/web3-providers/src/NextID/proof.ts
Labels: Test: Tested

#6286 fix: wrong call order of localeCompare
  packages/mask/src/plugins/ITO/SNSAdaptor/ExchangeTokenPanel.tsx
  packages/mask/src/plugins/ITO/SNSAdaptor/SwapDialog.tsx
  packages/shared/src/UI/components/ERC20TokenList/index.tsx
  packages/web3-shared/evm/hooks/useERC20TokensDetailedFromTokenLists.ts
Labels: Test: Tested

#6292 fix: css style
  packages/mask/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx
  packages/mask/src/plugins/Collectible/SNSAdaptor/PostListingDialog.tsx
  packages/mask/src/plugins/PoolTogether/UI/PoolTogetherView.tsx
  packages/mask/src/social-network-adaptor/twitter.com/collecting/identity.ts
Labels: Test: Tested

#6294 fix: config for network tab
  packages/mask/src/plugins/ITO/base.ts
Labels: Test: Tested

#6303 feat: use Cross-chain in production environment
  packages/plugins/CrossChainBridge/src/base.ts
Labels: Test: Tested

#6304 fix: send icon fill missing
  packages/dashboard/src/pages/Wallets/components/Balance/index.tsx
  packages/mask/src/components/CompositionDialog/CompositionUI.tsx
Labels: Test: Tested

#6306 fix: remove hard code width
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/CheckSecurityDialog.tsx
Labels: Test: Tested

#6308 fix: some 2.8.0 release ui issues
  packages/icons/general/Copy.tsx
  packages/mask/src/components/shared/SelectRecipients/ProfileInList.tsx
  packages/mask/src/plugins/NextID/SNSAdaptor/index.tsx
  packages/mask/src/plugins/NextID/components/BindingItem.tsx
Labels: Test: Tested

#6310 fix: timeline plugin render
  packages/mask/src/plugins/FindTruman/base.ts
  packages/mask/src/plugins/Gitcoin/base.ts
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketDialog.tsx
  packages/mask/src/plugins/RedPacket/base.ts
  packages/plugin-infra/src/hooks/useAvailablePlugins.ts
  packages/plugins/CyberConnect/src/base.tsx
Labels: Test: Tested

#6313 fix: fix compose bottom nav style
  packages/mask/src/components/CompositionDialog/CompositionUI.tsx
Labels: Test: Tested

#6319 fix: compose select show logic
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/components/CompositionDialog/EncryptionTargetSelector.tsx
  packages/mask/src/components/shared/SelectRecipients/SelectRecipients.tsx
  packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
Labels: Test: Tested

#6320 fix: tips some ui issues
  packages/mask/src/components/shared/VerifyWallet/CurrentWalletBox.tsx
  packages/mask/src/extension/popups/pages/Personas/VerifyWallet/index.tsx
  packages/mask/src/plugins/NextID/components/BindingItem.tsx
Labels: Test: Tested

#6339 chore: markdown ipfs renderer
  packages/mask/src/plugins/Snapshot/SNSAdaptor/hooks/useRemarkable.ts
Labels: Test: Tested

#6344 fix: connect wallet
  packages/icons/general/PopupClose.tsx
  packages/icons/general/SquareBack.tsx
  packages/icons/general/index.ts
  packages/mask/background/services/helper/popup-opener.ts
  packages/mask/src/extension/popups/components/NormalHeader/index.tsx
  packages/mask/src/extension/popups/pages/Personas/VerifyWallet/index.tsx
  packages/mask/src/extension/popups/pages/Wallet/ConnectWallet/index.tsx
  packages/mask/src/extension/popups/pages/Wallet/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx
Labels: Test: Tested

#6108 fix: savings plugin
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/shared-ui/locales/zh-CN.json
  packages/mask/src/extension/options-page/DashboardComponents/ActionButton.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsDialog.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsForm.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsTable.tsx
  packages/mask/src/web3/UI/TokenAmountPanel.tsx
Labels: Test: Tested
