Repository DimensionDev/Maskbook, pull requests merged in 2022-02, with the labels that each got.

#5291 feat: savings plugin and lido integration
  cspell.json
  packages/dashboard/src/locales/en-US.json
  packages/icons/plugins/Savings.tsx
  packages/icons/plugins/index.tsx
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/components/shared/ApplicationBoard.tsx
  packages/mask/src/components/shared/assets/savings.png
  packages/mask/src/extension/options-page/DashboardComponents/ActionButton.tsx
  packages/mask/src/plugin-infra/register.ts
  packages/mask/src/plugins/Savings/SNSAdaptor/IconURL.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsDialog.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsDialogStyles.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsForm.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsFormStyles.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsTable.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/assets/eth.png
  packages/mask/src/plugins/Savings/SNSAdaptor/assets/lido.png
  packages/mask/src/plugins/Savings/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Savings/Worker/apis/index.ts
  packages/mask/src/plugins/Savings/Worker/index.ts
  packages/mask/src/plugins/Savings/Worker/services.ts
  packages/mask/src/plugins/Savings/base.ts
  packages/mask/src/plugins/Savings/constants.ts
  packages/mask/src/plugins/Savings/index.ts
  packages/mask/src/plugins/Savings/messages.ts
  packages/mask/src/plugins/Savings/protocols/LDOProtocol.ts
  packages/mask/src/plugins/Savings/protocols/index.ts
  packages/mask/src/plugins/Savings/types.ts
  packages/mask/src/plugins/Trader/SNSAdaptor/trader/Trader.tsx
  packages/shared/package.json
  packages/shared/src/wallet/FormattedBalance.tsx
  packages/web3-constants/evm/savings.json
  packages/web3-contracts/abis/Lido.json
  packages/web3-contracts/types/Lido.d.ts
  packages/web3-shared/evm/constants/index.ts
  pnpm-lock.yaml
Labels: Type: Bounty

#5170 feat: CyberConnect
  cspell.json
  packages/dashboard/src/locales/en-US.json
  packages/dashboard/src/locales/zh-CN.json
  packages/dashboard/src/locales/zh-TW.json
  packages/dashboard/src/pages/Labs/constants.ts
  packages/dashboard/src/pages/Labs/index.tsx
  packages/icons/plugins/CyberConnect.tsx
  packages/icons/plugins/index.tsx
  packages/mask/package.json
  packages/mask/src/plugin-infra/register.ts
  packages/mask/src/utils/suspends/getAssetAsBlobURL.ts
  packages/plugin-infra/src/types.ts
  packages/plugins/CyberConnect/package.json
  packages/plugins/CyberConnect/src/SNSAdaptor/ConnectButton.tsx
  packages/plugins/CyberConnect/src/SNSAdaptor/FollowTab.tsx
  packages/plugins/CyberConnect/src/SNSAdaptor/Profile.tsx
  packages/plugins/CyberConnect/src/SNSAdaptor/index.tsx
  packages/plugins/CyberConnect/src/Worker/apis/index.ts
  packages/plugins/CyberConnect/src/Worker/index.ts
  packages/plugins/CyberConnect/src/assets/Context.png
  packages/plugins/CyberConnect/src/assets/CyberConnectIcon.tsx
  packages/plugins/CyberConnect/src/assets/Foundation.png
  packages/plugins/CyberConnect/src/assets/Opensea.png
  packages/plugins/CyberConnect/src/assets/Rarible.png
  packages/plugins/CyberConnect/src/assets/logo-white.svg
  packages/plugins/CyberConnect/src/base.tsx
  packages/plugins/CyberConnect/src/constants.ts
  packages/plugins/CyberConnect/src/env.d.ts
  packages/plugins/CyberConnect/src/index.ts
  packages/plugins/CyberConnect/src/messages.ts
  packages/plugins/CyberConnect/src/types.ts
  packages/plugins/CyberConnect/tsconfig.json
  packages/plugins/tsconfig.json
  packages/shared-base/src/utils/getAssetAsBlobURL.ts
  packages/shared-base/src/utils/index.ts
  packages/theme/src/constants.ts
  pnpm-lock.yaml
Labels: Blocked: Has Conflict, Type: Community

#5195 feat: Add IPFS, Swarm as Another Providers for The File Service into Mask
  .pnpmfile.cjs
  cspell.json
  packages/plugins/FileService/package.json
  packages/plugins/FileService/src/SNSAdaptor/MainDialog.tsx
  packages/plugins/FileService/src/SNSAdaptor/Preview.tsx
  packages/plugins/FileService/src/SNSAdaptor/components/Upload.tsx
  packages/plugins/FileService/src/SNSAdaptor/components/UploadDropArea.tsx
  packages/plugins/FileService/src/SNSAdaptor/components/Uploaded.tsx
  packages/plugins/FileService/src/SNSAdaptor/components/Uploading.tsx
  packages/plugins/FileService/src/SNSAdaptor/hooks/Exchange.tsx
  packages/plugins/FileService/src/Worker/arweave.ts
  packages/plugins/FileService/src/Worker/ipfs.ts
  packages/plugins/FileService/src/Worker/service.ts
  packages/plugins/FileService/src/Worker/swarm.ts
  packages/plugins/FileService/src/helpers.ts
  packages/plugins/FileService/src/locales/en-US.json
  packages/plugins/FileService/src/schema-v2.json
  packages/plugins/FileService/src/types.ts
  pnpm-lock.yaml
Labels: Blocked: Has Conflict, Type: Bounty

#5311 feat: the opensea token is-tweet bid, the token should be brought into the opensea token.
  cspell.json
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/shared-ui/locales/ko-KR.json
  packages/mask/shared-ui/locales/qya-AA.json
  packages/mask/shared-ui/locales/zh-CN.json
  packages/mask/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx
  packages/mask/src/plugins/Collectible/SNSAdaptor/SelectTokenListPanel.tsx
  packages/web3-shared/evm/hooks/useFungibleTokenWatched.tsx
Labels: Blocked: Has Conflict
