Repository DimensionDev/Maskbook, pull requests merged in 2022-03, with the labels that each got.

#5234 chore: token list domain
  packages/web3-constants/evm/token-list.json
  packages/web3-providers/src/token-list/index.ts
Labels: Blocked: Has Conflict

#5808 feat: next id web3 tab
  packages/mask/src/components/DataSource/useNextID.ts
  packages/mask/src/components/DataSource/usePersonaConnectStatus.ts
  packages/mask/src/components/InjectedComponents/ProfileTabContent.tsx
  packages/mask/src/components/InjectedComponents/ToolboxUnstyled.tsx
  packages/mask/src/plugins/NextID/SNSAdaptor/index.tsx
  packages/mask/src/plugins/NextID/components/BindDialog.tsx
  packages/mask/src/plugins/NextID/components/BindingItem.tsx
  packages/mask/src/plugins/NextID/components/NextIdPage.tsx
  packages/mask/src/plugins/NextID/components/UnbindConfirm.tsx
  packages/mask/src/plugins/NextID/components/UnbindDialog.tsx
  packages/mask/src/plugins/NextID/constants.ts
  packages/mask/src/plugins/NextID/locales/en-US.json
  packages/mask/src/plugins/NextID/locales/qya-AA.json
  packages/mask/src/plugins/NextID/locales/zh-CN.json
  packages/mask/src/plugins/NextID/types/index.ts
  packages/mask/src/plugins/NextID/types/nextId.ts
  packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts
  packages/plugin-infra/src/types.ts
  packages/shared-base/src/NextID/type.ts
Labels: Component: NextID

#5762 feat(plugin): add support for zora in collectible
  cspell.json
  packages/mask/src/plugins/Collectible/SNSAdaptor/CollectibleProviderIcon.tsx
  packages/mask/src/plugins/Collectible/base.ts
  packages/mask/src/plugins/Collectible/constants.ts
  packages/mask/src/plugins/Collectible/hooks/useAssetOrder.ts
  packages/mask/src/plugins/Collectible/pipes/index.ts
  packages/mask/src/plugins/Collectible/utils.ts
  packages/mask/src/plugins/EVM/services/Asset/index.ts
  packages/mask/src/plugins/EVM/services/NFT/index.ts
  packages/mask/src/resources/ZoraIcon.tsx
  packages/web3-providers/package.json
  packages/web3-providers/src/index.ts
  packages/web3-providers/src/zora/constants.ts
  packages/web3-providers/src/zora/index.ts
  packages/web3-providers/src/zora/queries.ts
  packages/web3-providers/src/zora/types.ts
  packages/web3-shared/evm/pipes/index.ts
  packages/web3-shared/evm/types/index.ts
  pnpm-lock.yaml
Labels: Type: Bounty, Bounty: Qualified, Component: Collectibles

#5798 feat(dex): integration mdex
  cspell.json
  packages/mask/src/plugins/Trader/apis/trader/index.ts
  packages/mask/src/plugins/Trader/constants/index.ts
  packages/mask/src/plugins/Trader/constants/mdex.ts
  packages/mask/src/plugins/Trader/pipes.ts
  packages/mask/src/plugins/Trader/trader/useAllTradeComputed.ts
  packages/mask/src/plugins/Trader/trader/useGetTradeContext.ts
  packages/mask/src/plugins/Trader/trader/useTradeCallback.ts
  packages/mask/src/plugins/Trader/trader/useTradeContext.ts
  packages/mask/src/plugins/Trader/types/trader.ts
  packages/public-api/src/web.ts
  packages/web3-constants/evm/trader.json
Labels: Type: Bounty, Component: DEX, Bounty: Reviewed, Bounty: Qualified

#5750 feat: integrate Conflux eSpace
  packages/dashboard/src/pages/Wallets/components/FungibleTokenTableRow/index.tsx
  packages/mask/src/components/shared/ApplicationBoard.tsx
  packages/mask/src/extension/popups/pages/Wallet/GasSetting/Prior1559GasSetting.tsx
  packages/mask/src/plugins/EVM/UI/Web3State/createGetLatestBalance.ts
  packages/mask/src/plugins/EVM/UI/Web3State/getAssetsFn.ts
  packages/mask/src/plugins/EVM/UI/Web3State/index.ts
  packages/mask/src/plugins/EVM/assets/conflux.png
  packages/mask/src/plugins/EVM/constants.ts
  packages/mask/src/plugins/NextID/base.ts
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketCreateNew.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketDialog.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketNft.tsx
  packages/mask/src/plugins/RedPacket/Worker/apis/chain.ts
  packages/mask/src/plugins/RedPacket/base.ts
  packages/mask/src/plugins/Trader/apis/trader/index.ts
  packages/mask/src/plugins/Trader/constants/0x.ts
  packages/mask/src/plugins/Trader/constants/dodo.ts
  packages/mask/src/plugins/Trader/constants/openocean.ts
  packages/mask/src/plugins/Trader/trader/0x/useTrade.ts
  packages/mask/src/plugins/Wallet/SNSAdaptor/GasSettingDialog/Prior1559GasSetting.tsx
  packages/public-api/src/web.ts
  packages/web3-constants/evm/coingecko.json
  packages/web3-constants/evm/coinmarketcap.json
  packages/web3-constants/evm/debank.json
  packages/web3-constants/evm/ethereum.json
  packages/web3-constants/evm/ito.json
  packages/web3-constants/evm/nft-red-packet.json
  packages/web3-constants/evm/red-packet.json
  packages/web3-constants/evm/rpc.json
  packages/web3-constants/evm/token-asset-base-url.json
  packages/web3-constants/evm/token-list.json
  packages/web3-constants/evm/token.json
  packages/web3-constants/evm/trader.json
  packages/web3-constants/evm/zerion.json
  packages/web3-shared/evm/assets/chains.json
  packages/web3-shared/evm/hooks/useBalance.ts
  packages/web3-shared/evm/pipes/index.ts
  packages/web3-shared/evm/types/index.ts
  packages/web3-shared/evm/utils/chainDetailed.ts
Labels: Component: Chain

#5873 feat: Go Plus Security plugin
  .i18n-codegen.json
  cspell.json
  packages/icons/general/Risk.tsx
  packages/mask/.webpack/config.ts
  packages/mask/package.json
  packages/mask/src/plugin-infra/register.js
  packages/plugin-infra/src/types.ts
  packages/plugins/GoPlusSecurity/package.json
  packages/plugins/GoPlusSecurity/src/Dashboard/index.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/CheckSecurityDialog.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/Common.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/DefaultPlaceholder.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/Footer.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/Loading.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/NotFound.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/RiskCard.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/SearchBox.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/Searching.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/SecurityPanel.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/TokenPanel.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/icons/Loading.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/icons/Logo.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/icons/SecurityIcon.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/index.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/rules.ts
  packages/plugins/GoPlusSecurity/src/Worker/index.ts
  packages/plugins/GoPlusSecurity/src/assets/security-icon.png
  packages/plugins/GoPlusSecurity/src/base.ts
  packages/plugins/GoPlusSecurity/src/constants.ts
  packages/plugins/GoPlusSecurity/src/env.d.ts
  packages/plugins/GoPlusSecurity/src/index.ts
  packages/plugins/GoPlusSecurity/src/locales/en-US.json
  packages/plugins/GoPlusSecurity/src/locales/index.ts
  packages/plugins/GoPlusSecurity/src/locales/ja-JP.json
  packages/plugins/GoPlusSecurity/src/locales/ko-KR.json
  packages/plugins/GoPlusSecurity/src/locales/languages.ts
  packages/plugins/GoPlusSecurity/src/locales/qya-AA.json
  packages/plugins/GoPlusSecurity/src/locales/zh-CN.json
  packages/plugins/GoPlusSecurity/src/locales/zh-TW.json
  packages/plugins/GoPlusSecurity/src/messages.ts
  packages/plugins/GoPlusSecurity/src/utils/helper.ts
  packages/plugins/GoPlusSecurity/tsconfig.json
  packages/shared-base/src/utils/requestComposition.ts
  packages/shared/src/hooks/useMenu.tsx
  packages/web3-providers/src/gopluslabs/constants.ts
  packages/web3-providers/src/gopluslabs/index.ts
  packages/web3-providers/src/index.ts
  packages/web3-providers/src/types.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: Test: Tested

#6006 fix: twitter nickname selector
  packages/mask/src/social-network-adaptor/twitter.com/collecting/identity.ts
  packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts
  packages/mask/src/social-network-adaptor/twitter.com/utils/user.ts
Labels: Test: Tested
