Repository DimensionDev/Maskbook, pull requests merged in 2022-04, with the labels that each got.

#6011 fix(instagram): can't open web3 tab
  packages/mask/src/components/InjectedComponents/ProfileTab.tsx
  packages/mask/src/social-network-adaptor/instagram.com/injection/ProfileTab.tsx
Labels: Test: Pending

#5982 fix(tip): hide tip button when evm is not actived
  packages/mask/src/components/InjectedComponents/ProfileTabContent.tsx
  packages/mask/src/plugins/EVM/constants.ts
  packages/mask/src/plugins/NextID/SNSAdaptor/index.tsx
  packages/mask/src/plugins/NextID/components/NextIdPage.tsx
  packages/mask/src/social-network-adaptor/twitter.com/injection/PostActions/index.tsx
  packages/plugin-infra/src/hooks/index.ts
  packages/plugin-infra/src/hooks/useAvailablePlugins.ts
  packages/plugin-infra/src/utils/createInjectHooksRenderer.tsx
Labels: Test: Tested

#6014 feat: go pocket feedback
  packages/plugins/GoPlusSecurity/package.json
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/NotFound.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/SecurityPanel.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/TokenPanel.tsx
  packages/plugins/GoPlusSecurity/src/locales/en-US.json
  packages/plugins/GoPlusSecurity/src/utils/helper.ts
  pnpm-lock.yaml
Labels: Test: Pending

#5899 fix: icon position in minds.com
  cspell.json
  packages/mask/src/components/InjectedComponents/PostDialogHint.tsx
  packages/mask/src/components/Welcomes/Banner.tsx
  packages/mask/src/resources/MaskIcon.tsx
  packages/mask/src/social-network-adaptor/minds.com/injection/PostDialogHint.tsx
  packages/mask/src/social-network-adaptor/minds.com/injection/SetupPrompt.tsx
  packages/mask/src/social-network-adaptor/minds.com/utils/selector.ts
Labels: Test: Tested

#6013 feat: tip NFT
  packages/dashboard/src/pages/Wallets/components/CollectibleList/index.tsx
  packages/icons/general/Drop2.tsx
  packages/icons/general/Edit2.tsx
  packages/icons/general/index.ts
  packages/mask/src/plugins/EVM/UI/Web3State/createNonFungibleToken.ts
  packages/mask/src/plugins/EVM/UI/Web3State/getAssetsFn.ts
  packages/mask/src/plugins/NextID/SNSAdaptor/index.tsx
  packages/mask/src/plugins/NextID/components/Tip/AddDialog.tsx
  packages/mask/src/plugins/NextID/components/Tip/NFTSection/NFTList.tsx
  packages/mask/src/plugins/NextID/components/Tip/NFTSection/index.tsx
  packages/mask/src/plugins/NextID/components/Tip/TipDialog.tsx
  packages/mask/src/plugins/NextID/components/Tip/TipForm.tsx
  packages/mask/src/plugins/NextID/components/Tip/TokenSection/index.tsx
  packages/mask/src/plugins/NextID/contexts/TargetChainIdContext.ts
  packages/mask/src/plugins/NextID/contexts/Tip/TipContext.ts
  packages/mask/src/plugins/NextID/contexts/Tip/TipTaskProvider.tsx
  packages/mask/src/plugins/NextID/contexts/Tip/useNftTip.ts
  packages/mask/src/plugins/NextID/contexts/Tip/useTipValidate.ts
  packages/mask/src/plugins/NextID/locales/en-US.json
  packages/mask/src/plugins/NextID/storage/index.ts
  packages/mask/src/plugins/NextID/types/tip.ts
  packages/plugin-infra/src/web3-types.ts
  packages/shared/src/UI/components/AssetPlayer/index.tsx
  packages/shared/src/UI/components/ImageIcon/index.tsx
  packages/shared/src/UI/components/NFTCardStyledAssetPlayer/index.tsx
  packages/shared/src/contexts/components/InjectedDialog.tsx
  packages/web3-shared/evm/hooks/useERC721ContractDetailed.ts
  packages/web3-shared/evm/hooks/useERC721TokenDetailed.ts
  packages/web3-shared/evm/hooks/useERC721TokenTransferCallback.ts
  packages/web3-shared/evm/utils/formatter.ts
Labels: Test: Tested

#6020 fix: should update tip status when next id verify status changed
  packages/mask/src/plugins/NextID/components/BindDialog.tsx
  packages/mask/src/plugins/NextID/components/Tip/TipButton.tsx
  packages/mask/src/plugins/NextID/components/UnbindDialog.tsx
  packages/web3-providers/src/NextID/helper.ts
  packages/web3-providers/src/NextID/proof.ts
Labels: Test: Tested

#6021 fix: hidden web3 tab page
  packages/mask/src/components/InjectedComponents/ProfileTabContent.tsx
Labels: Test: Tested

#6016 feat: add cross-chain-bridge plugin
  .i18n-codegen.json
  cspell.json
  packages/mask/.webpack/config.ts
  packages/mask/package.json
  packages/mask/src/plugin-infra/register.js
  packages/plugin-infra/src/types.ts
  packages/plugins/CrossChainBridge/README.md
  packages/plugins/CrossChainBridge/package.json
  packages/plugins/CrossChainBridge/src/Dashboard/index.tsx
  packages/plugins/CrossChainBridge/src/SNSAdaptor/CrossChainBridgeDialog.tsx
  packages/plugins/CrossChainBridge/src/SNSAdaptor/MaskIcon.tsx
  packages/plugins/CrossChainBridge/src/SNSAdaptor/assets/arbitrum-one-bridge.png
  packages/plugins/CrossChainBridge/src/SNSAdaptor/assets/boba-bridge.png
  packages/plugins/CrossChainBridge/src/SNSAdaptor/assets/cbridge.png
  packages/plugins/CrossChainBridge/src/SNSAdaptor/assets/cross-chain.png
  packages/plugins/CrossChainBridge/src/SNSAdaptor/assets/polygon-bridge.png
  packages/plugins/CrossChainBridge/src/SNSAdaptor/assets/rainbow-bridge.png
  packages/plugins/CrossChainBridge/src/SNSAdaptor/index.tsx
  packages/plugins/CrossChainBridge/src/Worker/index.ts
  packages/plugins/CrossChainBridge/src/base.ts
  packages/plugins/CrossChainBridge/src/constants.tsx
  packages/plugins/CrossChainBridge/src/env.d.ts
  packages/plugins/CrossChainBridge/src/index.ts
  packages/plugins/CrossChainBridge/src/locales/en-US.json
  packages/plugins/CrossChainBridge/src/locales/index.ts
  packages/plugins/CrossChainBridge/src/locales/ja-JP.json
  packages/plugins/CrossChainBridge/src/locales/ko-KR.json
  packages/plugins/CrossChainBridge/src/locales/languages.ts
  packages/plugins/CrossChainBridge/src/locales/qya-AA.json
  packages/plugins/CrossChainBridge/src/locales/zh-CN.json
  packages/plugins/CrossChainBridge/src/locales/zh-TW.json
  packages/plugins/CrossChainBridge/tsconfig.json
  packages/plugins/tsconfig.json
  pnpm-lock.yaml
  tsconfig.json
Labels: Test: Tested

#6033 fix: add token type check for token list
  packages/web3-shared/evm/hooks/useERC20TokenDetailed.ts
  packages/web3-shared/evm/hooks/useEthereumTokenType.ts
Labels: Test: Tested

#5990 feat: persona QR code
  packages/dashboard/src/pages/SignUp/steps/PreviewDialog.tsx
Labels: Test: Pending

#5987 fix: improve loading in collectible offers and order table
  packages/mask/src/plugins/Collectible/SNSAdaptor/ListingTab.tsx
  packages/mask/src/plugins/Collectible/SNSAdaptor/OfferTab.tsx
Labels: Test: Tested

#6050 fix: should filter asset which not on support chain
  packages/mask/src/plugins/EVM/UI/Web3State/getAssetsFn.ts
  packages/mask/src/plugins/Wallet/services/assets.ts
Labels: Test: Tested

#6044 fix(tip): adjust size of the badge of WalletIcon
  packages/mask/src/plugins/NextID/components/Tip/TipDialog.tsx
Labels: Test: Pending

#6041 fix: add ellipsis effect for nft contract name
  packages/mask/src/plugins/Wallet/SNSAdaptor/SelectNftContractDialog.tsx
Labels: Test: Tested

#6077 fix: incorrect plugin name
  packages/mask/src/plugins/RedPacket/SNSAdaptor/index.tsx
Labels: Test: Pending

#6042 fix: sprint2 ui issues
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketERC20Form.tsx
  packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
  packages/mask/src/social-network-adaptor/twitter.com/customization/custom.ts
  packages/mask/src/web3/UI/EthereumERC20TokenApprovedBoundary.tsx
Labels: Test: Tested

#6088 feat: popup connect wallet
  packages/dashboard/src/initialization/Dashboard.tsx
  packages/mask/src/components/shared/VerifyWallet/CurrentWalletBox.tsx
  packages/mask/src/components/shared/WalletStatusBox.tsx
  packages/mask/src/extension/background-script/EthereumServices/provider.ts
  packages/mask/src/extension/background-script/EthereumServices/providers/MaskWallet.ts
  packages/mask/src/extension/popups/pages/Wallet/SelectWallet/index.tsx
  packages/mask/src/extension/popups/pages/Wallet/VerifyWallet/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/WalletConnectQRCodeDialog/index.tsx
  packages/mask/src/plugins/Wallet/hooks/useSelectAccount.ts
  packages/mask/src/social-network/defaults/inject/PageInspector.tsx
Labels: Test: Failed

#6096 fix: incorrect text
  packages/mask/src/plugins/External/SNSAdaptor/index.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/index.tsx
Labels: Test: Tested

#6093 fix: lucky drop schema
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacket/index.tsx
  packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketInHistoryList.tsx
  packages/mask/src/plugins/RedPacket/schema.json
Labels: Test: Tested

#6095 fix: incorrect contracts query on dashboard
  packages/dashboard/src/pages/Personas/hooks/useContacts.ts
Labels: Test: Tested

#6073 feat: add <ConcealableTabs />
  packages/icons/general/LeftArrow.tsx
  packages/icons/general/RightArrow.tsx
  packages/icons/general/index.ts
  packages/mask/src/components/InjectedComponents/PageTab.tsx
  packages/mask/src/components/InjectedComponents/PageTabItem.tsx
  packages/mask/src/components/InjectedComponents/ProfileTabContent.tsx
  packages/mask/src/plugins/NextID/components/BindingItem.tsx
  packages/shared/src/UI/components/ConcealableTabs/index.tsx
  packages/shared/src/UI/components/index.ts
Labels: Test: Tested

#6078 fix: ITO history default icon
  packages/mask/src/plugins/ITO/SNSAdaptor/PoolInList.tsx
Labels: Test: Tested

#6062 fix(tip): set significant to 6 for formatting max amount
  packages/mask/src/plugins/NextID/components/Tip/TokenSection/index.tsx
  packages/mask/src/plugins/NextID/contexts/Tip/TipContext.ts
  packages/mask/src/plugins/NextID/contexts/Tip/TipTaskProvider.tsx
  packages/mask/src/plugins/NextID/contexts/Tip/useTokenTip.ts
  packages/mask/src/plugins/Trader/SNSAdaptor/trader/hooks/useGasConfig.ts
  packages/mask/src/web3/UI/TokenAmountPanel.tsx
  packages/web3-shared/evm/hooks/useGasPrice.ts
Labels: Test: Tested

#6055 feat: manage recent pending transactions
  cspell.json
  packages/dashboard/src/pages/Wallets/components/HistoryTableRow/index.tsx
  packages/dashboard/src/pages/Wallets/components/TransactionIcon/index.tsx
  packages/mask/package.json
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/components/shared/WalletStatusBox/TransactionList.tsx
  packages/mask/src/components/shared/WalletStatusBox/index.tsx
  packages/mask/src/components/shared/WalletStatusBox/usePendingTransactions.tsx
  packages/mask/src/extension/background-script/EthereumServices/rpc/index.ts
  packages/mask/src/plugins/Wallet/hooks/index.ts
  packages/mask/src/plugins/Wallet/hooks/useClearRecentTransactions.ts
  packages/mask/src/plugins/Wallet/hooks/useRecentTransactions.ts
  packages/mask/src/plugins/Wallet/hooks/useRemoveRecentTransaction.ts
  packages/shared-base-ui/src/hooks/index.ts
  packages/shared-base-ui/src/hooks/useAim.ts
  packages/web3-shared/evm/constants/getContractOwnerDomain.ts
  packages/web3-shared/evm/constants/index.ts
  packages/web3-shared/evm/types/index.ts
  pnpm-lock.yaml
Labels: Test: Pending

#6115 fix: if phantom is locked, might not able to open its popup
  packages/plugins/Solana/src/UI/SNSAdaptor/index.tsx
  packages/plugins/Solana/src/base.ts
  packages/plugins/Solana/src/constants.ts
  packages/plugins/Solana/src/wallet/connect.ts
Labels: Test: Tested

#6122 feat: new intial persona page
  packages/icons/general/AddUser.tsx
  packages/icons/general/PopupRestore.tsx
  packages/icons/general/index.ts
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/src/extension/popups/components/PopupFrame/index.tsx
  packages/mask/src/extension/popups/pages/Personas/ConnectedWallets/index.tsx
  packages/mask/src/extension/popups/pages/Personas/Home/UI.tsx
  packages/mask/src/extension/popups/pages/Personas/Home/index.tsx
Labels: Test: Tested

#6012 feat: tips entrance
  packages/icons/general/Tips.tsx
  packages/icons/general/index.ts
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/shared/kv-storage.ts
  packages/mask/src/components/DataSource/useNextID.ts
  packages/mask/src/components/InjectedComponents/SetupGuide.tsx
  packages/mask/src/components/shared/ApplicationBoard.tsx
  packages/mask/src/components/shared/ApplicationSettingPluginList.tsx
  packages/mask/src/components/shared/VerifyWallet/CurrentWalletBox.tsx
  packages/mask/src/components/shared/VerifyWallet/Steps.tsx
  packages/mask/src/plugin-infra/register.js
  packages/mask/src/plugins/NextID/components/NextIdPage.tsx
  packages/mask/src/plugins/NextID/components/Tip/TipButton.tsx
  packages/mask/src/plugins/NextID/components/Tip/TipTaskManager.tsx
  packages/mask/src/plugins/NextID/locales/en-US.json
  packages/mask/src/plugins/NextID/messages.ts
  packages/mask/src/plugins/Tips/SNSAdaptor/TipsEntranceDialog.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/AddWallet.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/Setting.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/Wallets.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/DisconnectDialog.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/EmptyStatus.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/VerifyAlertLine.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/WalletItem.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/WalletSwitch.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/WalletsByNetwork.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/index.tsx
  packages/mask/src/plugins/Tips/Worker/index.ts
  packages/mask/src/plugins/Tips/assets/Tip.png
  packages/mask/src/plugins/Tips/assets/copy.png
  packages/mask/src/plugins/Tips/assets/del.png
  packages/mask/src/plugins/Tips/assets/empty.png
  packages/mask/src/plugins/Tips/assets/emptyUnion.png
  packages/mask/src/plugins/Tips/assets/evmChains.png
  packages/mask/src/plugins/Tips/assets/link.png
  packages/mask/src/plugins/Tips/assets/wallet.png
  packages/mask/src/plugins/Tips/base.ts
  packages/mask/src/plugins/Tips/hooks/useKv.ts
  packages/mask/src/plugins/Tips/hooks/useProvedWallets.ts
  packages/mask/src/plugins/Tips/hooks/useTipsWalletsList.ts
  packages/mask/src/plugins/Tips/index.ts
  packages/mask/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/PluginProviderRender.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx
  packages/plugin-infra/src/types.ts
  packages/plugin-infra/src/web3-types.ts
  packages/plugins/Wallet/src/messages.ts
  packages/shared-base/src/Messages/Shared.ts
  packages/shared-base/src/NextID/type.ts
  packages/shared-base/src/Pure/index.ts
  packages/shared-base/src/utils/personas.ts
  packages/shared/src/UI/components/ApplicationEntry/index.tsx
  packages/shared/src/contexts/components/InjectedDialog.tsx
  packages/web3-providers/src/NextID/kv.ts
  packages/web3-providers/src/NextID/proof.ts
  packages/web3-providers/src/types.ts
Labels: Test: Tested

#6063 chore: improve backup info card
  packages/dashboard/src/components/Restore/BackupInfoCard.tsx
Labels: Test: Pending

#6043 fix: persona not preview in full page when printing
  packages/dashboard/src/pages/SignUp/steps/PreviewDialog.tsx
Labels: Test: Pending

#6152 fix: add loading and emtpy placeholder at savings plugin
  packages/icons/general/CircleLoading.tsx
  packages/icons/general/Direct.tsx
  packages/icons/general/index.ts
  packages/mask/shared-ui/locales/en-US.json
  packages/mask/shared-ui/locales/qya-AA.json
  packages/mask/shared-ui/locales/zh-CN.json
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsDialog.tsx
  packages/mask/src/plugins/Savings/SNSAdaptor/SavingsTable.tsx
Labels: Test: Tested

#6157 fix: hotfix release tips issues
  packages/mask/src/components/shared/VerifyWallet/Steps.tsx
  packages/mask/src/extension/popups/pages/Personas/VerifyWallet/index.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/TipsEntranceDialog.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/Setting.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/bodyViews/Wallets.tsx
  packages/mask/src/plugins/Tips/SNSAdaptor/components/DisconnectDialog.tsx
  packages/mask/src/plugins/Tips/base.ts
  packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx
  packages/web3-providers/src/NextID/constants.ts
Labels: Test: Tested

#6151 fix: some release bug
  packages/dashboard/src/pages/Wallets/components/FungibleTokenTableRow/index.tsx
  packages/mask/background/services/identity/persona/query.ts
Labels: Test: Tested

#6162 fix: ui issues of pending transactions
  packages/mask/src/components/shared/WalletStatusBox/TransactionList.tsx
  packages/mask/src/components/shared/WalletStatusBox/usePendingTransactions.tsx
Labels: Test: Tested

#6156 fix: ability to set pets, on non-evm chain
  packages/mask/src/plugins/Pets/base.tsx
Labels: Test: Pending

#6160 fix: remove duplicate profile in linked profile when restore
  packages/mask/background/database/persona/web.ts
Labels: Test: Tested

#6068 refactor: align loading component
  packages/icons/general/LoadingBase.tsx
  packages/icons/general/index.ts
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/components/Searching.tsx
  packages/plugins/GoPlusSecurity/src/SNSAdaptor/icons/Loading.tsx
  packages/theme/src/Components/LoadingBase/index.tsx
  packages/theme/src/Components/index.ts
  packages/theme/stories/atoms/LoadingBase.stories.tsx
Labels: Test: Pending

#6164 fix: bugfix for NFT description
  packages/mask/src/extension/popups/pages/Wallet/ContractInteraction/index.tsx
  packages/mask/src/plugins/Wallet/SNSAdaptor/WalletStatusDialog/TransactionDescription.tsx
Labels: Test: Pending

#6032 feat: twitter settings
  cspell.json
  packages/mask/src/social-network-adaptor/twitter.com/collecting/identity.ts
  packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts
  packages/web3-providers/src/twitter/index.ts
  packages/web3-providers/src/types.ts
Labels: Test: Tested

#6177 fix(tips): user might never config NextID
  packages/mask/src/plugins/Tips/hooks/usePublicWallets.ts
Labels: Test: Tested
